- name: Manage kubernetes servers
  hosts: all
  remote_user: root

  tasks:
    - name: Basic host setup
      import_tasks: "../tasks/basic.yaml"

    - name: Setup docker
      import_tasks: "../tasks/docker.yaml"

    - name: Setup kubernetes
      import_tasks: "../tasks/kubernetes.yaml"

  handlers:
    - name: Basic Handler
      import_tasks: "../handlers/basic.yaml"
