- name: Install required tools for Docker
  apt:
    name:
      [
        "apt-transport-https",
        "ca-certificates",
        "curl",
        "gnupg2",
        "software-properties-common",
      ]
    update_cache: true
    state: present

- name: Install Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
    update_cache: true

- name: Install Docker
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
    update_cache: true
    state: present

- name: Config Docker using systemd
  copy:
    dest: "/etc/docker/daemon.json"
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"]
      }

- name: Prune old Docker images cronjob
  cron:
    name: Prune old docker images
    minute: "1"
    hour: "4"
    user: root
    job: "docker system prune -af --filter 'until=48h' > /dev/null 2>&1"
    cron_file: ansible_docker-prune
#  - name: Prune old docker images
#    shell: docker system prune -af --filter 'until=48h'
